USE WALTRONICS;
GO

DROP TABLE Employee.Login;

CREATE TABLE Employee.Login (
	EmployeeID	UNIQUEIDENTIFIER	NOT NULL,
	Username	VARCHAR(50)			NOT NULL UNIQUE,
	Password	VARBINARY(8000)		NOT NULL
	PRIMARY KEY (EmployeeID),
	FOREIGN KEY (EmployeeID) REFERENCES	Employee.Employee (EmployeeID) ON DELETE CASCADE
);