USE WALTRONICS;
GO

DROP TABLE Session.Session;

CREATE TABLE Session.Session (
	ID				UNIQUEIDENTIFIER	NOT NULL,
	SessionID		UNIQUEIDENTIFIER	NOT NULL DEFAULT NEWID(),
	CreationDate	DATETIME			NOT NULL DEFAULT GETDATE(),
	Role			VARCHAR(50)			NOT NULL
	PRIMARY KEY (ID)
);